# Generated by Django 5.2.3 on 2025-07-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("post_id", models.CharField(blank=True, max_length=30, null=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("private", models.BooleanField(default=False)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of tags",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                (
                    "image4",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.TextField()),
                (
                    "content",
                    models.TextField(
                        help_text="Comment content must be less than 240 characters",
                        max_length=240,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Mark comment as deleted without removing it from the database",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.blogcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogpost",
                    ),
                ),
            ],
        ),
    ]
