# Generated by Django 5.1.5 on 2025-07-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=models.TextField(help_text='Comment content must be less than 240 characters', max_length=240),
        ),
    ]
