# Generated by Django 5.1.5 on 2025-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blogcomment_author_alter_blogcomment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Mark comment as deleted without removing it from the database'),
        ),
    ]
