# Generated by Django 5.2.3 on 2025-07-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_blogcomment_deleted"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogComment",
        ),
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
