# Generated by Django 5.1.5 on 2025-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of tags', max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
            ],
        ),
    ]
