# Generated by Django 5.1.5 on 2025-06-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_id',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
