# Generated by Django 5.2.3 on 2025-07-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_blogpost_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="post_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]

